# Site
name: "Cloud-Architekt.net"
title: "Cloud-Architekt.net"
description: "Blogging  "
logo: 'assets/images/logo.png'
favicon: 'assets/images/favlogo.png'
baseurl: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  thomas:
    name: Thomas Naunheim
    display_name: Thomas Naunheim
    avatar: 'assets/images/avatar.jpg'
    email: thomas@cloud-architekt.net
    web: https://www.cloud-architekt.net
    twitter: https://twitter.com/thomas_live
    description: "Cloud Architect and Engineer, Community Speaker"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
